env:
  browser: true
  es6: true
  webextensions: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  camelcase:
    - error
    - properties: never
  dot-notation:
    - error
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
